# Generated by Django 5.1.3 on 2025-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_restaurant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="average_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
