# Generated by Django 5.1.3 on 2025-11-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_alter_restaurant_average_rating"),
        ("restaurants", "0005_reviewreply"),
    ]

    operations = []
