# Generated by Django 5.2.5 on 2025-12-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurantimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantimage',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='restaurantimage',
            name='order',
        ),
    ]
